apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: tds-group-3
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
